name: Publish Terraform Cloud Module Action
description: This action creates a new private module in Terraform Cloud with a VCS connection to the current repository, if one does not already exist
author: takescoop
inputs:
  repo:
    description: The repository to publish. Format `owner/name`
    default: ${{ github.repository }}
  display-identifier:
    description: The display identifier for the repository
    default: ${{ github.repository }}
  tf-organization: 
    description: The Terraform Cloud organization name
    required: true
  tf-token:
    description: A Terraform Cloud API token
    required: true
  tf-host:
    description: The Terraform Cloud hostname
    default: app.terraform.io
  vcs-token-id: 
    description: Token ID of the Terraform Cloud VCS client used in the VCS connection (overrides vcs-name)
  vcs-name:
    description: Name of the Terraform Cloud VCS client for the repository (not used if vcs-token-id is passed)
    default: GitHub.com
outputs:
  module:
    description: Reference to the published module
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: upload-cloud
  color: purple
